name: dartivity
version: 0.2.0
author: Steve Hamblett<steve.hamblett@linux.com>
description: An iot client library for Dart
homepage: https://github.com/shamblett/dartivity

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  dartivity_messaging: '^1.0.0'
  dartivity_database: '^1.0.0'
  json_object_lite: '^2.1.1'
  uuid: '^1.0.3'

dev_dependencies:
  test: '^1.16.0-nullsafety.16'
  pana: '^0.14.10'
  build_runner: '^1.10.13'
  build_test: '^1.3.4'
  build_web_compilers: '^2.16.0'

