name: dartivity
version: 0.0.1
author: Steve Hamblett<steve.hamblett@linux.com>
description: An iot client library for Dart
homepage: https://github.com/shamblett/dartivity
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  gcloud: '>0.2.0'
  googleapis_auth: any
  json_object: '>=1.0.19'
  uuid: '>=0.5.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
