name: dartivity
description: An iot client library for Dart
version: 0.0.1
author: Steve Hamblett<steve.hamblett@linux.com>
homepage: https://github.com/shamblett/dartivity

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
 gcloud: '>0.2.0'
 googleapis_auth: 'any'
 uuid: '>=0.5.0'
 json_object: '>=1.0.19'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
